[package]
name = "cmd"
version = "0.1.0"
edition = "2021"

[dependencies]
kaminari = "0.1.1"
tokio = {version = "1", features = ["full"] }

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/server.rs"
